name: Build and test on featureBranch

on:
  push:
    branches: [ "featureBranch/**" ]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3  
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
        cache: maven
    - run: pwd & ls -al

        
    - run: mvn -B package --file backend/pom.xml

    